### ISSUE TITLE
v1 - issue with major only constraint

### ISSUE THREAD

**Issue by paulcacheux** [Masterminds/semver#188] opened 2022-09-29 06:55 UTC
Hello ! 

Surprisingly the following code outputs `true`: https://go.dev/play/p/wZGWuivr35Q
```go
package main

import (
	"fmt"

	"github.com/Masterminds/semver"
)

func main() {
	c, err := semver.NewConstraint("< 7")
	if err != nil {
		panic(err)
	}

	v, err := semver.NewVersion("7.0.0")
	if err != nil {
		panic(err)
	}

	fmt.Println(c.Check(v))
}
```

while https://go.dev/play/p/e-e-I7JDkKY outputs `false`
```go
package main

import (
	"fmt"

	"github.com/Masterminds/semver"
)

func main() {
	c, err := semver.NewConstraint("< 7.0.0")
	if err != nil {
		panic(err)
	}

	v, err := semver.NewVersion("7.0.0")
	if err != nil {
		panic(err)
	}

	fmt.Println(c.Check(v))
}
```

is this behavior intended ? Thanks !

**Comment by mattfarina** [comment] 2022-11-28 20:56
This behavior is intended. `< 7` and `< 7.0.0` are two different values. `< 7` is `< 7.x.x` which means anything that's a 7 major version.

Also note, your example uses semver v1. The current supported version is v3.

**Comment by paulcacheux** [comment] 2022-11-28 21:12
I strongly disagree that this is this simple:
- https://jubianchi.github.io/semver-check/#/%3C%207/7.0.0 for example the first result on google for "semver online" suggests a different result
- the v3 of this exact library outputs a different result https://go.dev/play/p/T4vVEYgj9vA

How could "< 7" ever mean "anything that's a 7 major version, it's in complete contradiction of the usual sense of "lower than"

**Comment by mattfarina** [comment] 2022-11-28 21:47
It was the intended behavior in v1 of the semver package. v3 of the package came out more than 3 years ago. Changing this behavior required making a major version change and this was one of the things we changed. You should no longer use the v1 package.

I understand you disagree with a design decision that was made more than 6 years ago and that was changed in v3 more than 3 years ago.

**Comment by mattfarina** [comment] 2022-11-29 16:07
Closing as the v1 release is no longer supported.

**Closed by mattfarina** 2022-11-29 16:07 UTC
Labels: question
